### ISSUE TITLE
GET issue. res multipart stream 

### ISSUE THREAD

**Issue by bourgeoa** [CxRes/node-solid-server#1]
@CxRes 
To create (res.send) a multi-part stream npm form-data https://www.npmjs.com/package/form-data should do the trick
https://stackoverflow.com/questions/50880939/creating-a-nodejs-server-that-send-response-with-multipart-form-data

If there are issues reading the multi-part stream
https://stackoverflow.com/questions/63465536/reading-multipartform-data-stream-correctly-nodejs

I don't know where you shall implement it. In NSS or in your PREP middlewares
It seems that the boundary is unique for the whole multi-part steam.

**Comment by CxRes** [comment]
Implemented in Express-PREP!
